import type { ResumeContent } from "@/types/resume";

const templates: Record<
  string,
  { color: string; accent: string; font: string; size: string; line: number }
> = {
  classic: { color: "#111827", accent: "#0c8ce4", font: "Georgia, serif", size: "11px", line: 1.45 },
  minimal: { color: "#1f2937", accent: "#111827", font: "Helvetica, Arial, sans-serif", size: "10.5px", line: 1.5 },
  premium: { color: "#0f172a", accent: "#7c3aed", font: "'Segoe UI', Roboto, sans-serif", size: "10.5px", line: 1.48 },
  executive: { color: "#0b1220", accent: "#b45309", font: "Garamond, 'Times New Roman', serif", size: "11px", line: 1.42 },
};

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildResumeHtmlDocument(params: {
  content: ResumeContent;
  templateId: string;
  name: string;
  title?: string;
}): string {
  const t = templates[params.templateId] ?? templates.classic;
  const { content, name, title } = params;
  const headerBorder = `3px solid ${t.accent}`;

  const experienceHtml = content.experience
    .map((job) => {
      const bullets = job.bullets
        .map((b) => `<li style="margin-bottom:3px;">${esc(b)}</li>`)
        .join("");
      return `
        <div style="margin-bottom:10px;">
          <div style="display:flex;justify-content:space-between;gap:12px;font-weight:700;">
            <span>${esc(job.role)}</span>
            <span style="font-weight:500;color:#6b7280;">${esc(job.dates)}</span>
          </div>
          <div style="font-style:italic;color:#374151;margin-bottom:4px;">${esc(job.company)}</div>
          <ul style="margin:0;padding-left:18px;">${bullets}</ul>
        </div>`;
    })
    .join("");

  const educationHtml = content.education
    .map(
      (ed) => `
      <div style="margin-bottom:6px;">
        <div style="display:flex;justify-content:space-between;gap:12px;font-weight:600;">
          <span>${esc(ed.school)}</span>
          <span style="font-weight:500;color:#6b7280;">${esc(ed.dates)}</span>
        </div>
        <div style="color:#374151;">${esc(ed.degree)}</div>
      </div>`,
    )
    .join("");

  const skills = content.skills.map(esc).join(" · ");

  const body = `
<div style="font-family:${t.font};color:${t.color};font-size:${t.size};line-height:${t.line};max-width:7.5in;margin:0 auto;">
  <header style="border-bottom:${headerBorder};padding-bottom:10px;margin-bottom:14px;">
    <h1 style="margin:0;font-size:22px;letter-spacing:0.3px;">${esc(name || "Professional Resume")}</h1>
    ${title ? `<p style="margin:6px 0 0;color:#4b5563;font-size:12px;">${esc(title)}</p>` : ""}
  </header>
  ${
    content.summary
      ? `<section style="margin-bottom:14px;">
    <h2 style="font-size:12px;text-transform:uppercase;letter-spacing:1.2px;color:${t.accent};margin:0 0 6px;">Summary</h2>
    <p style="margin:0;">${esc(content.summary)}</p>
  </section>`
      : ""
  }
  ${
    content.experience.length
      ? `<section style="margin-bottom:14px;">
    <h2 style="font-size:12px;text-transform:uppercase;letter-spacing:1.2px;color:${t.accent};margin:0 0 8px;">Experience</h2>
    ${experienceHtml}
  </section>`
      : ""
  }
  ${
    content.education.length
      ? `<section style="margin-bottom:14px;">
    <h2 style="font-size:12px;text-transform:uppercase;letter-spacing:1.2px;color:${t.accent};margin:0 0 8px;">Education</h2>
    ${educationHtml}
  </section>`
      : ""
  }
  ${
    content.skills.length
      ? `<section>
    <h2 style="font-size:12px;text-transform:uppercase;letter-spacing:1.2px;color:${t.accent};margin:0 0 6px;">Skills</h2>
    <p style="margin:0;">${skills}</p>
  </section>`
      : ""
  }
  <footer style="margin-top:22px;padding-top:8px;border-top:1px solid #e5e7eb;font-size:8px;color:#9ca3af;text-align:center;">
    Generated by CareerForge Pro — ATS-optimized output. Not for redistribution.
  </footer>
</div>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Resume</title>
<style>
  * { box-sizing: border-box; }
  body { margin: 0; padding: 0; background: #fff; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
</style>
</head>
<body>
${body}
</body>
</html>`;
}
